apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque #default for arbitary key-value pairs 
data:
    mongo-root-username: gDFlvn6jrSA= #base64 encoded
    mongo-root-password: rXHua2dhfKL= #base64 encoded
